<?php
$parameters = array(
        'db_driver' => 'pdo_mysql',
        'db_host' => 'localhost',
        'db_table_prefix' => 'xai_',
        'db_port' => '3306',
        'db_name' => 'xpxm',
        'db_user' => 'xai-user',
        'db_password' => 'XAIhey',
        'db_backup_tables' => 1,
        'db_backup_prefix' => 'bak_',
        'mailer_from_name' => 'Samuel Faith',
        'mailer_from_email' => 'sam@xperx.ai',
        'mailer_transport' => 'mautic.transport.amazon_api',
        'mailer_host' => null,
        'mailer_port' => null,
        'mailer_user' => null,
        'mailer_password' => null,
        'mailer_amazon_region' => 'us-east-1',
        'mailer_amazon_other_region' => null,
        'mailer_api_key' => null,
        'mailer_encryption' => null,
        'mailer_auth_mode' => null,
        'mailer_spool_type' => 'memory',
        'mailer_spool_path' => '%kernel.root_dir%/../var/spool',
        'secret_key' => 'f512b67c935a58b4141380b9f447ffaa3b61b5ba8b0b830e7cc73a5ac54e0852',
        'site_url' => 'http://edu2review.xperx.ai/index.php',
);